name: PR Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
              with:
                  node-version: ${{matrix.node-version}}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test --if-present
            - name: release dry-run
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run semantic-release:dry
